Enable use of an existing MySQL server by simply setting MYSQL_HOST in the .env file.
litespeedtech/ols-docker-env pull request #85
Opened 2024-09-22 10:24 UTC by josh208

Simply uncomment MYSQL_HOST in .env and set appropriately to use an existing MySQL server.

Additional change: By default, docker compose will NOT deploy the MySQL nor phpMyAdmin services (regardless of MYSQL_HOST setting. To deploy these the user must add '--profile database' to the docker compose command.

Documentation has been updated. 

I have done a full run-through and Wordpress fired right up. Also did a test without MYSQL_HOST set and with --profile database and got the stack running with the included MySQL/phpMyAdmin services.

2024-09-25 07:08 UTC, Code-Egg commented
Hi @josh208 
Both mysql and phpmyadmin are deployed and run by default. See the following example. 
```
git clone https://github.com/litespeedtech/ols-docker-env.git
cd ols-docker-env
docker compose up -d
```
Run `curl -Ik https://127.0.0.1:8443`, and it returns HTTP/1.1 200 OK. You can also open the phpmyadmin on the browser and log in with the db credential, which means both services are up and running. Can you give it a try, if it works, then we don't need to add `--profile`.

2024-09-25 16:18 UTC, josh208 commented
I am aware that phpMyAdmin and MySQL (technically MariaDB) are deployed by default. The purpose of this PR is to add an enhancement that allows the user to skip deployment of phpMyAdmin/MySQL and instead specify their own existing MySQL DB. It's not an uncommon use-case to have an existing MySQL instance already setup. I run my environment in Google Cloud and have a Google Cloud SQL instance that is far more robust than what would be run locally in a small cloud compute instance. Again, this is not an uncommon scenario.

2024-09-25 16:22 UTC, josh208 commented
It occurs to me that the confusion may come from the following statement that I made...

`Additional change: By default, docker compose will NOT deploy the MySQL nor phpMyAdmin services (regardless of MYSQL_HOST setting. To deploy these the user must add '--profile database' to the docker compose command.`

What I was saying is that with my change, phpMyAdmin / MySQL will not deploy by default and user muse add '--profile database' to do so. 

If this PR would otherwise be accepted, I could modify so that default behavior is only changed IF MYSQL_HOST is set.

2024-09-27 12:39 UTC, Code-Egg commented
Thanks for the details! I see what you mean now. The README is also a bit unclear, so I’ll take another look at it next week."
```
To use an existing MySQL server
docker compose up -d
Note: Be sure to uncomment, and set MYSQL_HOST in the .env file

To use the included MySQL Server (as well as phpMyAdmin)
docker compose --profile database up -d
Note: Be sure MYSQL_HOST is commented out in the .env file

Note: If you wish to run a single web server container, please see the [usage method here](https://github.com/litespeedtech/ols-dockerfiles#usage).
```

2024-09-30 03:11 UTC, Code-Egg requested changes
Please consider reverting the file and using the following instead, as I find it clearer.

## To use your own DB Server(including phpMyAdmin)
1. Comment out MYSQL_HOST from the .env file
2. Start containers with the command: `docker compose --profile database up -d`

2024-09-30 04:01 UTC, Code-Egg commented on bin/database.sh
For the help message, how about this: 
```
        -D, --domain [DOMAIN_NAME] -U, --user [xxx] -P, --password [xxx] -DB, --database [xxx], [-H DB_HOST_IP]
                Example: database.sh -D example.com -U USERNAME -P PASSWORD -DB DATABASENAME
                Example: database.sh -D example.com -U USERNAME -P PASSWORD -DB DATABASENAME -H 1.2.3.4
                Will create Database/username/password by given
        -R, --delete -DB, --database [xxx] -U, --user [xxx], [-H DB_HOST_IP]
                Example: database.sh -r -DB DATABASENAME -U USERNAME
                Example: database.sh -r -DB DATABASENAME -U USERNAME -H 1.2.3.4
                Will delete the database (require) and username (optional) by given
```

I can not find the -H or DB_HOST from the input, you probably need to fix it.

2024-09-30 04:07 UTC, Code-Egg commented on bin/demosite.sh
Please set -H ${MYSQL_HOST} as an optional service. 
Only run `bash bin/database.sh -D ${1} -H ${MYSQL_HOST} -U ${MYSQL_USER} -P ${MYSQL_PASSWORD} -DB ${MYSQL_DATABASE}` when user comment out MYSQL_HOST from the .env file.

2024-09-30 04:10 UTC, Code-Egg commented on docker-compose.yml
This will affect existing behavior with `docker compose up -d` command, both phpmyadmin and db don't run unless users add  --profile database parameter.

2025-03-03 06:55 UTC, closed without merging